name: CI_CD_Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # --- FASE 1: INTEGRACIÓN CONTINUA (CI) ---
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Generar cliente de Prisma y Ejecutar Tests
        run: |
          pnpm turbo run db:generate --continue || true
          pnpm --filter payment-service test -- --run
        env:
          NODE_ENV: "test"
          KAFKA_BROKER: "localhost:9092"
          STRIPE_WEBHOOK_SECRET: "whsec_test_secret"
          STRIPE_SECRET_KEY: "sk_test_mock"

  # --- FASE 2: DESPLIEGUE CONTINUO (CD) ---
  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Oracle Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/MicroservicesShop
            git pull origin main
            docker compose up -d --build
            echo "Despliegue exitoso 🚀"
